version: "3.8"
services:
  backend:
      image: "denzelawuah/springboot-react-fullstack:6.8.2021.13.48.43"
      ports:
        - "80:8080"
      restart: "always"
      environment:
        SPRING_PROFILES_ACTIVE: prod