version: "3.8"
services:
  backend:
      image: "denzelawuah/springboot-react-fullstack:3.8.2021.23.7.0"
      ports:
        - "80:8080"
      restart: "always"
      environment:
        SPRING_PROFILES_ACTIVE: prod