version: "3.8"
services:
  backend:
      image: "denzelawuah/springboot-react-fullstack:16.8.2021.16.3.21"
      ports:
        - "80:8080"
      restart: "always"
      environment:
        SPRING_PROFILES_ACTIVE: dev